/*
 * Copyright 2020 The Tesserae authors.
 *
 * For the full copyright and license information, please view the LICENSE file
 * that was distributed with this source code.
 */

/*
 * This file is automatically generated.
 */

#pragma once

struct doc_entry_flag {
  bool f_stage0_score = false;
  bool f_bm25_atire = false;
  bool f_bm25_atire_body = false;
  bool f_bm25_atire_title = false;
  bool f_bm25_atire_heading = false;
  bool f_bm25_atire_inlink = false;
  bool f_bm25_atire_a = false;
  bool f_bm25_trec3 = false;
  bool f_bm25_trec3_body = false;
  bool f_bm25_trec3_title = false;
  bool f_bm25_trec3_heading = false;
  bool f_bm25_trec3_inlink = false;
  bool f_bm25_trec3_a = false;
  bool f_bm25_trec3_kmax = false;
  bool f_bm25_trec3_kmax_body = false;
  bool f_bm25_trec3_kmax_title = false;
  bool f_bm25_trec3_kmax_heading = false;
  bool f_bm25_trec3_kmax_inlink = false;
  bool f_bm25_trec3_kmax_a = false;
  bool f_lm_dir_2500 = false;
  bool f_lm_dir_2500_body = false;
  bool f_lm_dir_2500_title = false;
  bool f_lm_dir_2500_heading = false;
  bool f_lm_dir_2500_inlink = false;
  bool f_lm_dir_2500_a = false;
  bool f_lm_dir_1500 = false;
  bool f_lm_dir_1500_body = false;
  bool f_lm_dir_1500_title = false;
  bool f_lm_dir_1500_heading = false;
  bool f_lm_dir_1500_inlink = false;
  bool f_lm_dir_1500_a = false;
  bool f_lm_dir_1000 = false;
  bool f_lm_dir_1000_body = false;
  bool f_lm_dir_1000_title = false;
  bool f_lm_dir_1000_heading = false;
  bool f_lm_dir_1000_inlink = false;
  bool f_lm_dir_1000_a = false;
  bool f_tfidf = false;
  bool f_tfidf_body = false;
  bool f_tfidf_title = false;
  bool f_tfidf_heading = false;
  bool f_tfidf_inlink = false;
  bool f_tfidf_a = false;
  bool f_prob = false;
  bool f_prob_body = false;
  bool f_prob_title = false;
  bool f_prob_heading = false;
  bool f_prob_inlink = false;
  bool f_prob_a = false;
  bool f_be = false;
  bool f_be_body = false;
  bool f_be_title = false;
  bool f_be_heading = false;
  bool f_be_inlink = false;
  bool f_be_a = false;
  bool f_dph = false;
  bool f_dph_body = false;
  bool f_dph_title = false;
  bool f_dph_heading = false;
  bool f_dph_inlink = false;
  bool f_dph_a = false;
  bool f_dfr = false;
  bool f_dfr_body = false;
  bool f_dfr_title = false;
  bool f_dfr_heading = false;
  bool f_dfr_inlink = false;
  bool f_dfr_a = false;
  bool f_stream_len = false;
  bool f_stream_len_body = false;
  bool f_stream_len_title = false;
  bool f_stream_len_heading = false;
  bool f_stream_len_inlink = false;
  bool f_stream_len_a = false;
  bool f_sum_stream_len = false;
  bool f_sum_stream_len_body = false;
  bool f_sum_stream_len_title = false;
  bool f_sum_stream_len_heading = false;
  bool f_sum_stream_len_inlink = false;
  bool f_sum_stream_len_a = false;
  bool f_min_stream_len = false;
  bool f_min_stream_len_body = false;
  bool f_min_stream_len_title = false;
  bool f_min_stream_len_heading = false;
  bool f_min_stream_len_inlink = false;
  bool f_min_stream_len_a = false;
  bool f_max_stream_len = false;
  bool f_max_stream_len_body = false;
  bool f_max_stream_len_title = false;
  bool f_max_stream_len_heading = false;
  bool f_max_stream_len_inlink = false;
  bool f_max_stream_len_a = false;
  bool f_mean_stream_len = false;
  bool f_mean_stream_len_body = false;
  bool f_mean_stream_len_title = false;
  bool f_mean_stream_len_heading = false;
  bool f_mean_stream_len_inlink = false;
  bool f_mean_stream_len_a = false;
  bool f_variance_stream_len = false;
  bool f_variance_stream_len_body = false;
  bool f_variance_stream_len_title = false;
  bool f_variance_stream_len_heading = false;
  bool f_variance_stream_len_inlink = false;
  bool f_variance_stream_len_a = false;
  bool f_tpscore = false;
  bool f_bm25_bigram_u8 = false;
  bool f_bm25_tp_dist_w100 = false;
  bool f_sdm = false;
  bool f_tag_title_qry_count = false;
  bool f_tag_heading_qry_count = false;
  bool f_tag_mainbody_qry_count = false;
  bool f_tag_inlink_qry_count = false;
  bool f_tag_title_count = false;
  bool f_tag_heading_count = false;
  bool f_tag_inlink_count = false;
  bool f_tag_applet_count = false;
  bool f_tag_object_count = false;
  bool f_tag_embed_count = false;
};
