/*
 * This file is automatically generated.
 */

#pragma once

struct statdoc_entry_flag {
    bool f_len              = false;
    bool f_title_len        = false;
    bool f_visterm_len      = false;
    bool f_url_len          = false;
    bool f_url_depth        = false;
    bool f_avg_term_len     = false;
    bool f_entropy          = false;
    bool f_stop_cover       = false;
    bool f_frac_stop        = false;
    bool f_frac_anchor_text = false;
    bool f_frac_vis_text    = false;
    bool f_frac_table_text  = false;
    bool f_frac_td_text     = false;
};
