#!/bin/bash

set -e

SPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BASE=$SPATH/..

awk 'BEGIN {
    print ";"
    print "; This file is automatically generated"
    print ";"
    print
    print "; path to an Indri index"
    print "indri_index = gov2"
    print
    print "; path to the forward index file"
    print "forward_index = gov2.fwd"
    print
    print "; path to the inverted index file"
    print "inverted_index = gov2.inv"
    print
    print "; path to the lexicon file"
    print "lexicon = gov2.lex"
    print
    print "; path to the static document feature file"
    print "static_doc_file = gov2.static"
    print
}
$1 ~ /bool/ {
    printf "; Enable/disable feature %s\n", $2
    printf "%s = 1\n", $2
    print ""
}
END {
}' $BASE/include/tesserae/doc_entry_flag.hpp \
   $BASE/include/tesserae/statdoc_entry_flag.hpp
