#!/bin/bash

set -e

SPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BASE=$SPATH/..
CLANGFMT=clang-format-6.0

for f in $BASE/include/text2feat/{doc_entry,statdoc_entry}.hpp; do
header=$(basename ${f%.hpp})_flag
awk '/^struct\s+(doc_entry|statdoc_entry)\s+{/ {
    foo = 1
    next
} /^\s+(size_t|double|int|uint[[:digit:]]+_t)/ {
    if (foo == 1) {
        print $0
    }
} /^}/ {
    if (foo == 1) {
        foo = 0
    }
}' $f \
    | awk -v type=$header 'BEGIN {
print "/*"
print " * This file is automatically generated."
print " */"
print
print "#pragma once"
print
print "struct " type " {"
}
{ print "bool f_" $2 " = false;"}
END {
print "};"
}' | $CLANGFMT -style=file > $BASE/include/text2feat/${header}.hpp
done
